---
- name: Update SSL certificate on GWEFA
  hosts: all
  become: true
  become_user: exadmn
  gather_facts: no
  vars:
    certificate_path: "/var/lib/awx/projects/ssl-exaservers.com/certificate.crt"
    private_key_path: "/var/lib/awx/projects/ssl-exaservers.com/privatekey.key"
    ca_bundle_path: "/var/lib/awx/projects/ssl-exaservers.com/ca_bundle.crt"

  tasks:
    - name: Remove exisiting files
      become: true
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/pki/tls/certs/exaservers.crt
        - /etc/pki/tls/private/exaservers.key
        - /etc/postfix/ssl/smtpd.pem

    - name: Copy SSL certificate
      copy:
        src: "{{ certificate_path }}"
        dest: "/etc/pki/tls/certs/exaservers.crt"

    - name: Copy SSL private key
      copy:
        src: "{{ private_key_path }}"
        dest: "/etc/pki/tls/private/exaservers.key"

    - name: Copy certificate.crt content
      slurp:
        src: /etc/pki/tls/certs/exaservers.crt
      register: cert_contents

    - name: Copy file.key content
      slurp:
        src: /etc/pki/tls/private/exaservers.key
      register: key_contents

    - name: Combine contents into smtpd file
      template:
        src: smtpd.j2
        dest: /etc/postfix/ssl/smtpd.pem
      vars:
        certificate_content: "{{ cert_contents['content'] | b64decode }}"
        key_content: "{{ key_contents['content'] | b64decode }}"

    - name: Restart httpd service
      command: systemctl restart httpd

    - name: Restart postfix service
      command: systemctl restart postfix
